package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;

@Entity
@Table(name="students")

public class Student {


	@Id
	@Column(name = "oid")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int oid;
	@Column(name = "name")
	private String name;
	@Column(name = "age")
	private int age;
	@Column(name = "phone")
	private String phone;
	 @OneToMany( fetch=FetchType.EAGER,orphanRemoval=false)
	//@OneToMany
	//@JoinColumn(name = "student_id")
	 private List<Book> books = new ArrayList<>();
	 
	public Student(){
		
	}
	
	public List<Book> getBooks() {
		return books;
	}

	public void setBooks(List<Book> books) {
		this.books = books;
	}

	public Student(String name ,int age,String phone ) {
		
		
		this.name = name;
		this.phone = phone;
		this.age = age;
	
	}
	public Student(int id ,String name ,int age,String phone ) {
		
		this.oid =id;
		this.name = name;
		this.phone = phone;
		this.age = age;
	
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}

	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}


	public int getOid() {
		return oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}
	
	
}
